WORD_SCRIPT = wordcount.py
TXT_FILES = $(wildcard books/*.txt)
DAT_FILES=$(patsubset books/%.txt, %.bat, $(TXT_FILES))

analysis.zip : $(DAT_FILES) $(WORD_SCRIPT)
	zip $@ $^

.PHONY : variables
variables : 
	echo TXT_FILES: $(TXT_FILES)
	echo DAT_FILES: $(DAT_FILES)
	
.PHONY : dats
dats : $(DAT_FILES)

# count words
%.dat : books/%.txt $(WORD_SCRIPT)
	python $(WORD_SCRIPT) $< $*.dat
	
.PHONY : clean	
clean : 
	rm -f $(DAT_FILES)
	rm -f analysis.zip